__author__ = 'ilya'

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# https://projecteuler.net/problem=2
# Answer 4613732

i = 1
fibonacci = [1, 2, 3]
fibonacciEven = [2]
#print(len(fibonacci))

while i < 200:
    #i = fibonacci[len(fibonacci) - 1];
    print(i)
    i = i +1
    nextNum = fibonacci[len(fibonacci) - 2] + fibonacci[len(fibonacci) - 1]
    fibonacci.append(nextNum)
    if (nextNum > 4000000):
        break
    if nextNum % 2 == 0:
        fibonacciEven.append(nextNum)

print(fibonacci[len(fibonacci)-2])
fibonacci.remove(fibonacci[len(fibonacci)-1])
print(sum(fibonacci))
# 9227463   - 19
print(fibonacci)
print(fibonacciEven)
print("Answer = " + str(sum(fibonacciEven)))
